#!/usr/bin/env python


def configure(conf):
  conf.env.m_mlibraries.append('t_meshdef')


def build(bld):
  bld.objects(
    target   = 't_meshdef',
    includes = ['.','../../mkernel'],
    source   = ['t_meshdef.cpp'] )

