#!/usr/bin/env python


def configure(conf):
  conf.env.m_mlibraries.append('ls_pardiso')
  conf.env['LIB_PARDISO']       = ['pardiso410_GNU443_X86-64','lapack','gfortran']
  conf.env['LIBPATH_PARDISO']   = ['/home/pmaciel/Documents/dev/external/pardiso']
  conf.env['RPATH_PARDISO']     = ['/home/pmaciel/Documents/dev/external/pardiso']
  conf.env['LINKFLAGS_PARDISO'] = ['-fopenmp']


def build(bld):
  bld.shlib(
    target   = 'ls_pardiso',
    includes = ['.','../../mkernel'],
    source   = ['ls_pardiso.cpp'],
    use      = ['PARDISO'] )

