#!/usr/bin/env python


def configure(conf):
  conf.env.m_mlibraries.append('t_plas')


def build(bld):
  bld.shlib(
    target   = 't_plas',
    includes = ['.','../../mkernel'],
    source   = ['t_plas.cpp','plas.cpp'],
    use      = ['plas'] )

