#!/usr/bin/env python


def configure(conf):
  conf.env.m_mlibraries.append('t_plas')


def build(bld):
  # PLaS library and interface module
  bld.shlib(target='plas',   includes=['.','../../mkernel'], source=['plas.cpp'])
  bld.shlib(target='t_plas', includes=['.','../../mkernel'], source=['t_plas.cpp'], use=['plas'])

