#!/usr/bin/env python


def configure(conf):
  conf.env.m_mlibraries.append('mtransform_collection')


def build(bld):
  bld.shlib(
    target   = 'mtransform_collection',
    includes = ['.','../../mkernel','../format_smurf'],
    source   = [
      't_avgsolution.cpp',
      't_debug.cpp',
      't_extrude.cpp',
      't_fix.cpp',
      't_flip.cpp',
      't_geo.cpp',
      't_info.cpp',
      't_lap2d.cpp',
      't_manip.cpp',
      't_math.cpp',
      't_minmax.cpp',
      't_ncompress.cpp',
      't_probe.cpp',
      't_ren.cpp',
      't_simplex.cpp',
      't_solution.cpp',
      't_surfmap.cpp',
      't_walldistance.cpp',
      't_zmerge.cpp' ] )

