#!/usr/bin/env python


def configure(ctx):
  ctx.env.m_mlibraries.append('mtransform_collection')


def build(ctx):
  ctx.new_task_gen(
    features = 'cxx cshlib',
    target   = 'mtransform_collection',
    includes = ['.','../../mkernel','../format_smurf'],
    source   = [
      't_avgsolution.cpp',
      't_debug.cpp',
      't_extrude.cpp',
      't_fix.cpp',
      't_geo.cpp',
      't_info.cpp',
      't_lap2d.cpp',
      't_manip.cpp',
      't_math.cpp',
      't_ren.cpp',
      't_simplex.cpp',
      't_solution.cpp',
      't_surfmap.cpp',
      't_walldistance.cpp',
      't_zmerge.cpp' ] )

