#!/usr/bin/env python


def configure(conf):
  conf.env.m_mlibraries.append('msmurf')


def build(bld):

  # smurf static/dynamic library (not to use with m)
  l = bld.stlib(
    target   = 'smurf',
    includes = ['.'],
    source   = ['smurf.cpp'] )
  bld.shlib(
    target   = l.target,
    includes = l.includes,
    source   = l.source )

  # msmurf library (to use with m)
  bld.shlib(
    target   = 'msmurf',
    includes = l.includes + ['../../mkernel'],
    source   = l.source   + ['f_smurf.cpp','f_plt.cpp'] )

  # p smurf filter executable (does not use m)
  bld.program(
    target   = 'p',
    use      = ['smurf'],
    includes = ['.'],
    source   = ['p.cpp',
      'smurf.cpp',                              # smurf
      'ext/fparser.cc','ext/fpoptimizer.cc'] )  # function parser

