#!/usr/bin/env python


def configure(conf):
  conf.env.m_mlibraries.append('t_laplace')


def build(bld):
  bld.shlib(
    target   = 't_laplace',
    includes = ['.','../../mkernel'],
    source   = ['t_laplace.cpp'] )

