#!/usr/bin/env python


def configure(conf):
  conf.env.m_mlibraries.append('io_cgns')


def build(bld):
  bld.objects(
    target   = 'io_cgns',
    includes = ['../../mkernel'],
    source   = ['f_cgns.cpp'] )

