#!/usr/bin/env python


def configure(ctx):
  ctx.env.m_mlibraries.append('mformat_collection')


def build(ctx):
  ctx.new_task_gen(
    features = 'cxx cshlib',
    name     = 'mformat_collection',
    target   = 'mformat_collection',
    includes = ['.','../../mkernel'],
    source   = ['f_cfmesh.cpp','f_miotras.cpp','f_neu.cpp','f_steven.cpp'] )

