#!/usr/bin/env python


def configure(conf):
  conf.env.m_mlibraries.append('mformat_collection')


def build(bld):
  bld.shlib(
    target   = 'mformat_collection',
    includes = ['.','../../mkernel'],
    source   = [
      'f_cfmesh.cpp',
      'f_miotras.cpp',
      'f_muphys.cpp',
      'f_neu.cpp',
      'f_steven.cpp',
      'f_xpl.cpp' ] )

