#!/usr/bin/env python


def configure(ctx):
  ctx.env.m_mlibraries.append('ls_gmres')


def build(ctx):
  ctx.new_task_gen(
    features = 'cxx cshlib',
    name     = 'ls_gmres',
    target   = 'ls_gmres',
    includes = ['.','../mkernel'],
    source   = ['ls_gmres.cpp'] )

