#!/usr/bin/env python


def configure(conf):
  conf.env.m_mlibraries.append('collection_io')


def build(bld):
  bld.shlib(
    target   = 'collection_io',
    includes = ['.','../../mkernel'],
    source   = [
      'f_cfmesh.cpp',
      'f_miotras.cpp',
      'f_muphys.cpp',
      'f_steven.cpp',
      'f_xpl.cpp' ] )

