#!/usr/bin/env python


def configure(conf):
  conf.env.m_mlibraries.append('io_smurf')


def build(bld):

  # smurf library (does not use m)
  bld.stlib(
    target   = 'smurf',
    includes = ['.'],
    source   = ['smurf.cpp'] )

  # smurf filter (does not use m)
  bld.program(
    target   = 'p',
    includes = ['.'],
    source   = ['p.cpp','ext/fparser.cc','ext/fpoptimizer.cc'],
    use      = ['smurf'] )

  # plugin
  bld.shlib(
    target   = 'io_smurf',
    includes = ['.','../../mkernel'],
    source   = ['f_smurf.cpp','f_plt.cpp'],
    use      = ['smurf'] )

