#!/usr/bin/env python


def configure(conf):
  conf.env.m_mlibraries.append('ls_aztec')


def build(bld):
  bld.shlib(
    target   = 'ls_aztec',
    use      = ['aztec'],
    lib      = ['lapack','blas','gfortran'],
    includes = ['.','aztec','../../mkernel'],
    source   = ['ls_aztec.cpp'] )

