#!/usr/bin/env python


def configure(ctx):
  ctx.env.m_mlibraries.append('ls_aztec')


def build(ctx):
  ctx.new_task_gen(
    features = 'cxx cshlib',
    name     = 'ls_aztec',
    target   = 'ls_aztec',
    includes = ['.','aztec','../../mkernel'],
    source   = ['ls_aztec.cpp'],
    uselib_local = 'aztec' )

