#!/usr/bin/env python


def configure(conf):
  conf.env.m_mlibraries.append('ls_wsmp')
  conf.env['LIB_WSMP']       = ['wsmp64','blas','gfortran']
  conf.env['LIBPATH_WSMP']   = ['/home/pmaciel/Documents/dev/external/wsmp']
  conf.env['RPATH_WSMP']     = ['/home/pmaciel/Documents/dev/external/wsmp']
  conf.env['LINKFLAGS_WSMP'] = ['-fopenmp']


def build(bld):
  bld.shlib(
    target   = 'ls_wsmp',
    includes = ['.','../../mkernel'],
    source   = ['ls_wsmp.cpp'],
    use      = ['WSMP'] )

