#!/usr/bin/env python


def configure(ctx):
  ctx.env.m_mlibraries.append('ls_wsmp')
  ctx.env['LIB_WSMP']       = ['wsmp64','blas','gfortran']
  ctx.env['LIBPATH_WSMP']   = ['/home/pedro/workspace/external/wsmp/lib/GNU']
  ctx.env['RPATH_WSMP']     = ['/home/pedro/workspace/external/wsmp/lib/GNU']
  ctx.env['LINKFLAGS_WSMP'] = ['-fopenmp']


def build(ctx):
  ctx.new_task_gen(
    features = 'cxx cshlib',
    name     = 'ls_wsmp',
    target   = 'ls_wsmp',
    includes = ['.','../../mkernel'],
    source   = ['ls_wsmp.cpp'],
    uselib   = ['WSMP'] )

